"""add_project_direction

Revision ID: 195e3f74503e
Revises: 4dd9be79a2d9
Create Date: 2026-07-18 13:42:15.492460
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '195e3f74503e'
down_revision: str | None = '4dd9be79a2d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("source_mode", sa.String(length=32), server_default="original", nullable=False),
    )
    op.add_column(
        "projects", sa.Column("direction", sa.JSON(), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'direction')
    op.drop_column('projects', 'source_mode')
    # ### end Alembic commands ###
