"""add_login_throttles

Revision ID: 4dd9be79a2d9
Revises: a3fa16f80558
Create Date: 2026-07-18 13:33:18.187123
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4dd9be79a2d9'
down_revision: str | None = 'a3fa16f80558'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_throttles',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_throttles')
    # ### end Alembic commands ###
