"""enforce_single_adopted_script_records

Revision ID: 6ea11edecd5b
Revises: 922280780566
Create Date: 2026-07-18 14:26:10.894796
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6ea11edecd5b'
down_revision: str | None = '922280780566'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_script_blueprint_one_adopted', 'script_blueprints', ['project_id'], unique=True, sqlite_where=sa.text('adopted = 1'))
    op.create_index('uq_script_document_one_adopted', 'script_document_revisions', ['project_id', 'scene_id'], unique=True, sqlite_where=sa.text("status = 'adopted'"))
    op.create_index('uq_script_core_one_adopted', 'script_story_core_candidates', ['project_id'], unique=True, sqlite_where=sa.text("status = 'adopted'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_script_core_one_adopted', table_name='script_story_core_candidates', sqlite_where=sa.text("status = 'adopted'"))
    op.drop_index('uq_script_document_one_adopted', table_name='script_document_revisions', sqlite_where=sa.text("status = 'adopted'"))
    op.drop_index('uq_script_blueprint_one_adopted', table_name='script_blueprints', sqlite_where=sa.text('adopted = 1'))
    # ### end Alembic commands ###
