"""add_script_creation_domain

Revision ID: 974e88a8d594
Revises: 25a7de31b846
Create Date: 2026-07-18 14:05:45.265554
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '974e88a8d594'
down_revision: str | None = '25a7de31b846'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_document_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=120), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('base_revision_id', sa.String(length=36), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_script_document_request'),
    sa.UniqueConstraint('project_id', 'scene_id', 'revision_number', name='uq_script_scene_revision')
    )
    op.create_index('ix_script_document_scene_status', 'script_document_revisions', ['project_id', 'scene_id', 'status'], unique=False)
    op.create_table('script_story_core_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('angles', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision_feedback', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'generation', 'ordinal', name='uq_script_core_generation_ordinal')
    )
    op.create_index('ix_script_core_project_status', 'script_story_core_candidates', ['project_id', 'status'], unique=False)
    op.create_table('script_structure_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=False),
    sa.Column('proposed_episodes', sa.JSON(), nullable=False),
    sa.Column('impact', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_script_structure_request')
    )
    op.create_table('script_blueprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('story_core_candidate_id', sa.String(length=36), nullable=False),
    sa.Column('adopted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_core_candidate_id'], ['script_story_core_candidates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_script_blueprint_version')
    )
    op.create_table('script_blueprint_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blueprint_id', sa.String(length=36), nullable=False),
    sa.Column('anchor_key', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['script_blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_id', 'anchor_key', name='uq_script_blueprint_anchor_key')
    )
    op.create_index('ix_script_blueprint_anchor_kind', 'script_blueprint_anchors', ['blueprint_id', 'kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_script_blueprint_anchor_kind', table_name='script_blueprint_anchors')
    op.drop_table('script_blueprint_anchors')
    op.drop_table('script_blueprints')
    op.drop_table('script_structure_candidates')
    op.drop_index('ix_script_core_project_status', table_name='script_story_core_candidates')
    op.drop_table('script_story_core_candidates')
    op.drop_index('ix_script_document_scene_status', table_name='script_document_revisions')
    op.drop_table('script_document_revisions')
    # ### end Alembic commands ###
