"""initial_v7_schema

Revision ID: a3fa16f80558
Revises:
Create Date: 2026-07-18 13:30:41.759059
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a3fa16f80558'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_tenant_created', 'audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_table('memory_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('memory_entry_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_audit_scope', 'memory_audit', ['tenant_id', 'project_id', 'created_at'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('credential_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('credential_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('credential_key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_providers_key')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_token_quota', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_tiers_code')
    )
    op.create_table('language_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('agentscope_class', sa.String(length=80), nullable=False),
    sa.Column('min_tier_id', sa.String(length=36), nullable=False),
    sa.Column('input_price_per_million', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('output_price_per_million', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['min_tier_id'], ['tiers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_language_models_key')
    )
    op.create_index('ix_language_models_provider_enabled', 'language_models', ['provider_id', 'enabled'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('medium', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_tenant_id_id', 'projects', ['tenant_id', 'id'], unique=False)
    op.create_table('token_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('monthly_available', sa.Integer(), nullable=False),
    sa.Column('credits_available', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tier', name='uq_token_accounts_scope')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_tenant_id_id', 'users', ['tenant_id', 'id'], unique=False)
    op.create_table('agent_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role_key', sa.String(length=80), nullable=False),
    sa.Column('serialized_state', sa.JSON(), nullable=False),
    sa.Column('context_tokens', sa.Integer(), nullable=True),
    sa.Column('context_limit', sa.Integer(), nullable=True),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'role_key', name='uq_agent_state_scope')
    )
    op.create_table('agent_template_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('soul', sa.String(), nullable=False),
    sa.Column('default_model_id', sa.String(length=36), nullable=False),
    sa.Column('fallback_model_id', sa.String(length=36), nullable=True),
    sa.Column('tool_keys', sa.JSON(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_model_id'], ['language_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['language_models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_key', 'version', name='uq_agent_template_role_version')
    )
    op.create_index('ix_agent_template_role_published', 'agent_template_versions', ['role_key', 'published'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role_key', sa.String(length=80), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_index('ix_memory_entries_scope', 'memory_entries', ['tenant_id', 'project_id', 'role_key'], unique=False)
    op.create_table('project_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('waiting_reason', sa.String(length=120), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_project_runs_idempotency')
    )
    op.create_index('ix_project_runs_status_updated', 'project_runs', ['status', 'updated_at'], unique=False)
    op.create_index('ix_project_runs_tenant_project', 'project_runs', ['tenant_id', 'project_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_tenant_id_id', 'sessions', ['tenant_id', 'id'], unique=False)
    op.create_table('workspace_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_name', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'storage_name', name='uq_workspace_file_storage_name')
    )
    op.create_index('ix_workspace_files_tenant_project', 'workspace_files', ['tenant_id', 'project_id'], unique=False)
    op.create_table('project_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('correlation_id', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['project_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'event_key', name='uq_project_events_run_key'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_project_events_run_sequence')
    )
    op.create_index('ix_project_events_tenant_run_sequence', 'project_events', ['tenant_id', 'run_id', 'sequence'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['workspace_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_chunks_scope', 'rag_chunks', ['tenant_id', 'project_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    op.create_index('ix_refresh_tokens_session_id_status', 'refresh_tokens', ['session_id', 'status'], unique=False)
    op.create_table('runtime_config_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('template_version_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_version_id'], ['agent_template_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_runtime_config_snapshot_run')
    )
    op.create_table('usage_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('monthly_reserved', sa.Integer(), nullable=False),
    sa.Column('credits_reserved', sa.Integer(), nullable=False),
    sa.Column('actual_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['project_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_usage_reservation_idempotency')
    )
    op.create_index('ix_usage_reservations_run', 'usage_reservations', ['run_id', 'status'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('monthly_delta', sa.Integer(), nullable=False),
    sa.Column('credits_delta', sa.Integer(), nullable=False),
    sa.Column('monthly_before', sa.Integer(), nullable=False),
    sa.Column('monthly_after', sa.Integer(), nullable=False),
    sa.Column('credits_before', sa.Integer(), nullable=False),
    sa.Column('credits_after', sa.Integer(), nullable=False),
    sa.Column('actual_tokens', sa.Integer(), nullable=True),
    sa.Column('reversal_of_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['usage_reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['credit_ledger.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'operation', name='uq_credit_ledger_operation')
    )
    op.create_index('ix_credit_ledger_tenant_created', 'credit_ledger', ['tenant_id', 'created_at'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('framework_event_id', sa.String(length=160), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('agent_role', sa.String(length=80), nullable=False),
    sa.Column('model_key', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('input_price_per_million', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('output_price_per_million', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['usage_reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['project_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'framework_event_id', name='uq_token_usage_event')
    )
    op.create_index('ix_token_usage_tenant_project', 'token_usage', ['tenant_id', 'project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_usage_tenant_project', table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index('ix_credit_ledger_tenant_created', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index('ix_usage_reservations_run', table_name='usage_reservations')
    op.drop_table('usage_reservations')
    op.drop_table('runtime_config_snapshots')
    op.drop_index('ix_refresh_tokens_session_id_status', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_rag_chunks_scope', table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index('ix_project_events_tenant_run_sequence', table_name='project_events')
    op.drop_table('project_events')
    op.drop_index('ix_workspace_files_tenant_project', table_name='workspace_files')
    op.drop_table('workspace_files')
    op.drop_index('ix_sessions_tenant_id_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_project_runs_tenant_project', table_name='project_runs')
    op.drop_index('ix_project_runs_status_updated', table_name='project_runs')
    op.drop_table('project_runs')
    op.drop_index('ix_memory_entries_scope', table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index('ix_agent_template_role_published', table_name='agent_template_versions')
    op.drop_table('agent_template_versions')
    op.drop_table('agent_states')
    op.drop_index('ix_users_tenant_id_id', table_name='users')
    op.drop_table('users')
    op.drop_table('token_accounts')
    op.drop_index('ix_projects_tenant_id_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_language_models_provider_enabled', table_name='language_models')
    op.drop_table('language_models')
    op.drop_table('tiers')
    op.drop_table('tenants')
    op.drop_table('providers')
    op.drop_index('ix_memory_audit_scope', table_name='memory_audit')
    op.drop_table('memory_audit')
    op.drop_index('ix_audit_log_tenant_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
