"""separate_run_stream_events

Revision ID: deb076cf010b
Revises: 27a0a5d6e21a
Create Date: 2026-07-18 16:03:26.003091
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "deb076cf010b"
down_revision: str | None = "27a0a5d6e21a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_stream_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_key", sa.String(length=160), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("correlation_id", sa.String(length=120), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["project_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "event_key", name="uq_run_stream_event_key"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_run_stream_sequence"),
    )
    op.create_index(
        "ix_run_stream_tenant_run_sequence",
        "run_stream_events",
        ["tenant_id", "run_id", "sequence"],
        unique=False,
    )
    op.execute(
        """
        INSERT INTO run_stream_events
            (id, tenant_id, project_id, run_id, sequence, event_key, event_type,
             correlation_id, payload, occurred_at)
        SELECT id, tenant_id, project_id, run_id, sequence, event_key, event_type,
               correlation_id, payload, occurred_at
        FROM project_events
        WHERE run_id IS NOT NULL
        """
    )
    op.execute("DELETE FROM project_events WHERE run_id IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO project_events
            (id, tenant_id, project_id, run_id, stream_key, sequence, event_key,
             event_type, correlation_id, payload, occurred_at)
        SELECT id, tenant_id, project_id, run_id, 'run:' || run_id, sequence,
               event_key, event_type, correlation_id, payload, occurred_at
        FROM run_stream_events
        """
    )
    op.drop_index("ix_run_stream_tenant_run_sequence", table_name="run_stream_events")
    op.drop_table("run_stream_events")
    # ### end Alembic commands ###
