"""add_script_blueprint_candidates

Revision ID: 1f0dfd3d45de
Revises: 974e88a8d594
Create Date: 2026-07-18 14:07:29.653550
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1f0dfd3d45de'
down_revision: str | None = '974e88a8d594'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_blueprint_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('story_core_candidate_id', sa.String(length=36), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_core_candidate_id'], ['script_story_core_candidates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_script_blueprint_request')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_blueprint_candidates')
    # ### end Alembic commands ###
