"""add_review_findings

Revision ID: 27a0a5d6e21a
Revises: 5f6a2b92f491
Create Date: 2026-07-18 14:54:41.720327
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "27a0a5d6e21a"
down_revision: str | None = "5f6a2b92f491"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("medium", sa.String(length=20), nullable=False),
        sa.Column("unit_id", sa.String(length=120), nullable=False),
        sa.Column("base_revision_id", sa.String(length=36), nullable=False),
        sa.Column("element_id", sa.String(length=120), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("anchor_type", sa.String(length=40), nullable=False),
        sa.Column("anchor_id", sa.String(length=120), nullable=False),
        sa.Column("anchor_note", sa.String(), nullable=False),
        sa.Column("original_excerpt", sa.String(), nullable=False),
        sa.Column("locator", sa.JSON(), nullable=False),
        sa.Column("diagnosis", sa.String(), nullable=False),
        sa.Column("suggestion", sa.String(), nullable=False),
        sa.Column("suggested_patch", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stale_reason", sa.String(), nullable=True),
        sa.Column("superseded_by", sa.String(length=36), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("trace_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "idempotency_key", name="uq_review_finding_request"),
    )
    op.create_index(
        "ix_review_findings_filter",
        "review_findings",
        ["project_id", "status", "severity", "domain"],
        unique=False,
    )
    op.create_index(
        "ix_review_findings_unit",
        "review_findings",
        ["project_id", "unit_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_findings_unit", table_name="review_findings")
    op.drop_index("ix_review_findings_filter", table_name="review_findings")
    op.drop_table("review_findings")
    # ### end Alembic commands ###
