"""add_novel_creation_domain

Revision ID: 5f6a2b92f491
Revises: 6ea11edecd5b
Create Date: 2026-07-18 14:34:29.976959
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5f6a2b92f491"
down_revision: str | None = "6ea11edecd5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "novel_document_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("chapter_id", sa.String(length=120), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("base_revision_id", sa.String(length=36), nullable=True),
        sa.Column("blocks", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "chapter_id", "revision_number", name="uq_novel_chapter_revision"
        ),
        sa.UniqueConstraint("project_id", "idempotency_key", name="uq_novel_document_request"),
    )
    op.create_index(
        "ix_novel_document_chapter_status",
        "novel_document_revisions",
        ["project_id", "chapter_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_novel_document_one_adopted",
        "novel_document_revisions",
        ["project_id", "chapter_id"],
        unique=True,
        sqlite_where=sa.text("status = 'adopted'"),
    )
    op.create_table(
        "novel_story_core_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("premise", sa.String(), nullable=False),
        sa.Column("point_of_view", sa.String(length=120), nullable=False),
        sa.Column("narrative_constraints", sa.JSON(), nullable=False),
        sa.Column("angles", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision_feedback", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "generation", "ordinal", name="uq_novel_core_generation_ordinal"
        ),
        sa.UniqueConstraint(
            "project_id", "idempotency_key", "ordinal", name="uq_novel_core_request_ordinal"
        ),
    )
    op.create_index(
        "ix_novel_core_project_status",
        "novel_story_core_candidates",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_novel_core_one_adopted",
        "novel_story_core_candidates",
        ["project_id"],
        unique=True,
        sqlite_where=sa.text("status = 'adopted'"),
    )
    op.create_table(
        "novel_structure_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("base_version", sa.Integer(), nullable=False),
        sa.Column("proposed_volumes", sa.JSON(), nullable=False),
        sa.Column("impact", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "idempotency_key", name="uq_novel_structure_request"),
    )
    op.create_table(
        "novel_blueprint_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("story_core_candidate_id", sa.String(length=36), nullable=False),
        sa.Column("draft", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["story_core_candidate_id"], ["novel_story_core_candidates.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "idempotency_key", name="uq_novel_blueprint_request"),
    )
    op.create_table(
        "novel_blueprints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("story_core_candidate_id", sa.String(length=36), nullable=False),
        sa.Column("adopted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["story_core_candidate_id"], ["novel_story_core_candidates.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version", name="uq_novel_blueprint_version"),
    )
    op.create_index(
        "uq_novel_blueprint_one_adopted",
        "novel_blueprints",
        ["project_id"],
        unique=True,
        sqlite_where=sa.text("adopted = 1"),
    )
    op.create_table(
        "novel_blueprint_anchors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("blueprint_id", sa.String(length=36), nullable=False),
        sa.Column("anchor_key", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["blueprint_id"], ["novel_blueprints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blueprint_id", "anchor_key", name="uq_novel_blueprint_anchor_key"),
    )
    op.create_index(
        "ix_novel_blueprint_anchor_kind",
        "novel_blueprint_anchors",
        ["blueprint_id", "kind"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_novel_blueprint_anchor_kind", table_name="novel_blueprint_anchors")
    op.drop_table("novel_blueprint_anchors")
    op.drop_index(
        "uq_novel_blueprint_one_adopted",
        table_name="novel_blueprints",
        sqlite_where=sa.text("adopted = 1"),
    )
    op.drop_table("novel_blueprints")
    op.drop_table("novel_blueprint_candidates")
    op.drop_table("novel_structure_candidates")
    op.drop_index(
        "uq_novel_core_one_adopted",
        table_name="novel_story_core_candidates",
        sqlite_where=sa.text("status = 'adopted'"),
    )
    op.drop_index("ix_novel_core_project_status", table_name="novel_story_core_candidates")
    op.drop_table("novel_story_core_candidates")
    op.drop_index(
        "uq_novel_document_one_adopted",
        table_name="novel_document_revisions",
        sqlite_where=sa.text("status = 'adopted'"),
    )
    op.drop_index("ix_novel_document_chapter_status", table_name="novel_document_revisions")
    op.drop_table("novel_document_revisions")
    # ### end Alembic commands ###
